In [1]:
import main

In [2]:
import pandas

In [10]:
bne_simple = main.BNE(30 , can_distribute = False)
bne_wo_delegation = main.BNE(30 , assigned_can_delegate = False)
bne_w_information_loss = main.BNE(4)
glob = main.GLOB()

prdgms = [glob , bne_simple , bne_wo_delegation , bne_w_information_loss]

# Was ist neu?

1. Frühere Annahme : je komprimierter die Kodierung desto besser.
    1. Prädikate sind die wichtigsten Elemente im Satz
    1. Alles wird unter ihnen eingefügt
    1. **Problem:** Tags wie 01++6ARGM-LOC++9ARG1 kommen einmal vor.
2. Wie kann man Signalfrequenz steigern?
3. Indizes verursachen Probleme : ++3ARG0 and ++6ARG0 haben dieselbe Bedeutung jedoch unterschiedliche Verweise.
    1. Lsg : Wichtigeren Wörtern im Satz neue Zahlen vergeben. 
    2. Zugeordnete Zahlen dann kann man noch auf eine maximale Zahl beschränken. Informationsverlust.
4. \%50.4 aller Wörter haben keine Tags. Kann man diese sinnvoll benutzen?
    1. Vorschlag: Die Wörter zwischen zwei Verben V1 und V2 können für die Kodierung von Tags von V1 verwendet werden. Ähnelt BIO/IOB Tagging.

In [11]:
print(main.dataset.entries[50].get_sentence())

As the survey cited in the above - linked article shows , most Google users do n't intend to use Gmail , and Google is n't even as popular as Yahoo! and AOL .

In [12]:
entry = main.dataset.get_by_query(lambda x : len(x) < 11)[0]
# entry = main.dataset.entries[2]
a = bne_simple.encode(entry)
aDlg =  bne_wo_delegation.encode(entry)
b = bne_w_information_loss.encode(entry)
c = glob.encode(entry)
df = pandas.DataFrame({"Words" : entry.get_words() , "Old": c , "Simple": a, "Delegated" :aDlg, "W/InfoLoss" : b ,"BIO" : main.bio(b)})
df

   Words               Old               Simple Delegated W/InfoLoss BIO
0   From                 _                    _         _          _
1    the                 _                    _         _          _
2     AP                 _                    1         1          1
3  comes  03++2ARG2++5ARG1  V03++1,ARG2++2,ARG1       V03        V03
4   this                 _                    _  ++1,ARG2   ++1,ARG2
5  story                 _                    2         2  2++2,ARG1
6      :                 _                    _  ++2,ARG1          _

## Probleme

1. Diese neue Art ist ungewöhnlich für Menschen. Ist es sicher zu sagen dass dies schlecht ist? Erfahrungen aus dem Feld? 
2. Je weniger leere Tokens desto weniger brauchen wir DEPREL zu nutzen. Kann mann dann andere Datensätze benutzen?

In [13]:
stats = []
tokencounts = []

for i in prdgms:
    tokenstat , tokencnt = main.dataset.get_freq_for_paradigm(i)
    stats.append(tokenstat)
    tokencounts.append(tokencnt)

freqs = pandas.DataFrame({"Old": stats[0] , "Simple": stats[1], "Delegated" :stats[2], "W/InfoLoss" : stats[3]})
freqs.style.set_caption("So viel kommen unterschiedliche Tokens vor:")
print(tokencounts)
freqs

[80.2051853030062, 54.04405916971528, 30.91697152855098, 34.984889454429776]

     Old  Simple  Delegated  W/InfoLoss
0      0       0          0           0
1   2515    2188       1497         808
2    193     200        170         119
3     65      58         78          53
4     27      39         41          32
5     26      24         39          15
6     16      22         25          17
7      8       9         21          16
8      6      10         11          22
9     10      11          8           9
10     1       3          7          13
11     7       5         10           4
12     4       3          5           8
13     0       2          8           5
14     3       1          8           4
15     0       2          6           7
16     1       6          3           6
17     1       5          2           5
18     2       1          3           4
19     2       2          4           2
20     1       4          2           1
21     1       1          3           2
22     0       0          1           0
23     1       1          3           3
24     0       0          0           4
25     2       1          3           3
26     0       1          3           1
27     0       2          3           1
28     0       0          0           2
29     0       1          0           0
30     1       0          1           1
31     0       0          2           1
32     0       0          1           0
33     0       0          1           2
34     0       0          2           0
35     0       1          0           0
36     3       0          1           1
37     0       0          0           2
38     0       0          2           0
39     0       0          1           2